version: "3.4"

services:
  # This service runs the tests and shuts down. This can also be used as
  # entrypoint into the container by running `docker-compose run prio_processor
  # bash`.
  prio_processor:
    build:
      context: .
  server_a:
    build:
      context: .
    working_dir: /app
    command: "true"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_A?"missing credentials"}:/tmp/.credentials
    environment:
      - DATA_CONFIG=/app/config/content.json
      - SERVER_ID=A
      - SHARED_SECRET=m/AqDal/ZSA9597GwMM+VA==
      - PRIVATE_KEY_HEX=624BFDF22F729BBFD762B3D61930B876F3711B200A10F620FEAC6FD792A2BD08
      - PUBLIC_KEY_HEX_INTERNAL=AB0008BDE17581D3C45CA8CEACB3F7CE6FB48FEF98AA78597A6955633F54D628
      - PUBLIC_KEY_HEX_EXTERNAL=68499CBDCAE6B06CAC0C86D255A609B6AFF66A56087803CFE4BD998C7E20220C
      - BUCKET_INTERNAL_PRIVATE=gs://moz-fx-prio-dev-a-private
      - BUCKET_INTERNAL_SHARED=gs://moz-fx-prio-dev-a-shared
      - BUCKET_EXTERNAL_SHARED=gs://moz-fx-prio-dev-b-shared
      - BUCKET_PREFIX=test-data/v1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - SUBMISSION_DATE
  server_b:
    build:
      context: .
    working_dir: /app
    command: "true"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_B?"missing credentials"}:/tmp/.credentials
    environment:
      - DATA_CONFIG=/app/config/content.json
      - SERVER_ID=B
      - SHARED_SECRET=m/AqDal/ZSA9597GwMM+VA==
      - PRIVATE_KEY_HEX=86EBA021A49C18B1D2885BCAE8C1985D14082F4A130F4862FD3E77DDD0518D3D
      - PUBLIC_KEY_HEX_INTERNAL=68499CBDCAE6B06CAC0C86D255A609B6AFF66A56087803CFE4BD998C7E20220C
      - PUBLIC_KEY_HEX_EXTERNAL=AB0008BDE17581D3C45CA8CEACB3F7CE6FB48FEF98AA78597A6955633F54D628
      - BUCKET_INTERNAL_PRIVATE=gs://moz-fx-prio-dev-b-private
      - BUCKET_INTERNAL_SHARED=gs://moz-fx-prio-dev-b-shared
      - BUCKET_EXTERNAL_SHARED=gs://moz-fx-prio-dev-a-shared
      - BUCKET_PREFIX=test-data/v1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - SUBMISSION_DATE
  admin:
    build:
      context: .
    working_dir: /app
    command: "true"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_ADMIN?"missing credentials"}:/tmp/.credentials
    environment:
      - DATA_CONFIG=/app/config/content.json
      - ORIGIN_CONFIG=/app/config/telemetry_origin_data_inc.json
      - PUBLIC_KEY_HEX_INTERNAL=AB0008BDE17581D3C45CA8CEACB3F7CE6FB48FEF98AA78597A6955633F54D628
      - PUBLIC_KEY_HEX_EXTERNAL=68499CBDCAE6B06CAC0C86D255A609B6AFF66A56087803CFE4BD998C7E20220C
      - BUCKET_INTERNAL_PRIVATE=gs://moz-fx-prio-dev-a-private
      - BUCKET_EXTERNAL_PRIVATE=gs://moz-fx-prio-dev-b-private
      - BUCKET_PREFIX=test-data/v1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/.credentials
      - DATASET=telemetry
      - TABLE=content_blocking_dev
      - BQ_REPLACE=true
      # Set the default project for inserting rows
      - CLOUDSDK_CORE_PROJECT
      - SUBMISSION_DATE
